services:
  experiment-config:
    extends:
      file: docker-compose-base.yaml
      service: experiment-config
    ports:
      - 8080:8080
    build:
      context: ./
      target: development
    # Mount our host Directory to the docker container
    # Mount (.) current directory to the docker container src/app
    # reflect file changes from host to container
    volumes:
      - .:/src/experiment-config
      - /src/experiment-config/node_modules
    command: npm run start:dev
  experiment-config-dapr:
    extends:
      file: docker-compose-base.yaml
      service: experiment-config-dapr
    volumes:
      - "./.dapr/dapr-config-minimal.yaml:/config.yaml"
      - "./.dapr/components:/components"
  placement:
    image: "daprio/dapr"
    command: ["./placement", "-port", "50006"]
    ports:
      - 50006:50006