# Docker Compose Configuration
# visit https://docs.docker.com/compose/

version: '3.8'
services:
  # app service for your backend
  experiment-config:
    restart: unless-stopped
    healthcheck:
      test: >
        curl -f -X GET http://localhost:8080/health || exit 1
      interval: 1s
      timeout: 10s
      retries: 20
      start_period: 3s
    build:
      context: ./
      target: production
  experiment-config-dapr:
    image: "daprio/daprd:edge"
    network_mode: "service:experiment-config"
    command:
      [
        "./daprd",
        "--app-id",
        "experiment-config",
        "--app-port",
        "8080",
        "--dapr-http-port",
        "3500",
        "-placement-host-address",
        "placement:50006",
        "--config",
        "/config.yaml",
        "--resources-path",
        "/components",
      ]